spring:
  application:
    name: subsync

  datasource:
    # 1. We point to Port 3306 and the 'subsync' database you just created
    url: jdbc:mysql://localhost:3306/subsync?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

    # 2. Standard XAMPP User
    username: root

    # 3. Standard XAMPP Password (Empty)
    password: ""

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
