spring:
  application:
    name: subsync

  datasource:
    url: jdbc:postgresql://localhost:5432/subsync
    username: postgres
    password: password # Adjust this to your local PostgreSQL password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
